version: "3.1"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass