CREATE TABLE IF NOT EXISTS machine
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        TIMESTAMP,
    drink       VARCHAR(100),
    volume      INT,
    sugar       INT,
    coffee_type VARCHAR(100)
);